head.load("js/lib/jquery.js", 
					"js/lib/cycle.js",
					"js/common.js",
					"js/lib/fotorama.js",
					"js/lib/jquery-ui.min.js",
					"js/lib/slick.min.js",
					"js/lib/jquery.mousewheel.js",
					"js/lib/jquery.jscrollpane.min.js"
					);
